<?php

namespace ContainerWk8XfVF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OeI1KgwService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.OeI1Kgw' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.OeI1Kgw'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'factory' => ['privates', 'Pimcore\\Bundle\\DataImporterBundle\\Mapping\\MappingConfigurationFactory', 'getMappingConfigurationFactoryService', true],
            'importProcessingService' => ['privates', 'Pimcore\\Bundle\\DataImporterBundle\\Processing\\ImportProcessingService', 'getImportProcessingServiceService', true],
        ], [
            'factory' => 'Pimcore\\Bundle\\DataImporterBundle\\Mapping\\MappingConfigurationFactory',
            'importProcessingService' => 'Pimcore\\Bundle\\DataImporterBundle\\Processing\\ImportProcessingService',
        ]);
    }
}
