pimcore_data_hub:
    configurations:
        Runways:
            general:
                active: true
                type: dataImporterDataObject
                name: Runways
                description: ''
                group: ''
                path: null
                modificationDate: 1699215777
                createDate: 1699215530
            loaderConfig:
                type: upload
                settings:
                    uploadFilePath: Runways/upload.import
            interpreterConfig:
                type: csv
                settings:
                    skipFirstRow: true
                    delimiter: ','
                    enclosure: '"'
                    escape: \
            resolverConfig:
                elementType: dataObject
                dataObjectClassId: '3'
                loadingStrategy:
                    type: notLoad
                createLocationStrategy:
                    type: staticPath
                    settings:
                        path: /newimport
                locationUpdateStrategy:
                    type: staticPath
                    settings:
                        path: /newimport
                publishingStrategy:
                    type: alwaysPublish
            processingConfig:
                executionType: parallel
                idDataIndex: '0'
                doDeltaCheck: true
                cleanup:
                    doCleanup: true
                    strategy: unpublish
            mappingConfig:
                -
                    label: 'id [0]'
                    dataSourceIndex:
                        - '0'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: id_runways
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: 'airport_ref [1]'
                    dataSourceIndex:
                        - '1'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: airport_ref
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: 'airport_ident [2]'
                    dataSourceIndex:
                        - '2'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: airport_ident
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: 'length_ft [3]'
                    dataSourceIndex:
                        - '3'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: length_ft
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: 'width_ft [4]'
                    dataSourceIndex:
                        - '4'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: width_ft
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: 'surface [5]'
                    dataSourceIndex:
                        - '5'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: surface
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: 'lighted [6]'
                    dataSourceIndex:
                        - '6'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: lighted
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: 'closed [7]'
                    dataSourceIndex:
                        - '7'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: closed
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: 'le_ident [8]'
                    dataSourceIndex:
                        - '8'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: le_ident
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: 'le_latitude_deg [9]'
                    dataSourceIndex:
                        - '9'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: le_latitude_deg
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: 'le_longitude_deg [10]'
                    dataSourceIndex:
                        - '10'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: le_longitude_deg
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: 'le_elevation_ft [11]'
                    dataSourceIndex:
                        - '11'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: le_elevation_ft
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: 'le_heading_degT [12]'
                    dataSourceIndex:
                        - '12'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: le_heading_degT
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: 'le_displaced_threshold_ft [13]'
                    dataSourceIndex:
                        - '13'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: le_displaced_threshold_ft
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: 'he_ident [14]'
                    dataSourceIndex:
                        - '14'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: he_ident
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: 'he_latitude_deg [15]'
                    dataSourceIndex:
                        - '15'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: he_latitude_deg
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: 'he_longitude_deg [16]'
                    dataSourceIndex:
                        - '16'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: he_longitude_deg
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: 'he_elevation_ft [17]'
                    dataSourceIndex:
                        - '17'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: he_elevation_ft
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: 'he_heading_degT [18]'
                    dataSourceIndex:
                        - '18'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: he_heading_degT
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: 'he_displaced_threshold_ft [19]'
                    dataSourceIndex:
                        - '19'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: he_displaced_threshold_ft
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
            executionConfig:
                scheduleType: recurring
                cronDefinition: ''
                scheduledAt: ''
            permissions:
                user: {  }
                role: {  }
            workspaces: {  }
