<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWk8XfVF\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWk8XfVF/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWk8XfVF.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWk8XfVF\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWk8XfVF\App_KernelDevDebugContainer([
    'container.build_hash' => 'Wk8XfVF',
    'container.build_id' => '43d4b2d3',
    'container.build_time' => 1699380972,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWk8XfVF');
