<?php

namespace ContainerF3OUZLB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_N015f8rService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.N015f8r' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.N015f8r'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'classificationStoreDataTypeService' => ['privates', 'Pimcore\\Bundle\\DataImporterBundle\\Mapping\\Type\\ClassificationStoreDataTypeService', 'getClassificationStoreDataTypeServiceService', true],
        ], [
            'classificationStoreDataTypeService' => 'Pimcore\\Bundle\\DataImporterBundle\\Mapping\\Type\\ClassificationStoreDataTypeService',
        ]);
    }
}
