<?php

namespace ContainerF3OUZLB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConfigDataObjectControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Pimcore\Bundle\DataImporterBundle\Controller\ConfigDataObjectController' shared autowired service.
     *
     * @return \Pimcore\Bundle\DataImporterBundle\Controller\ConfigDataObjectController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Controller/Controller.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Controller/UserAwareController.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Controller/Traits/JsonHelperTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/data-importer/src/Controller/ConfigDataObjectController.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Helper/TemporaryFileHelperTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/data-importer/src/Preview/PreviewService.php';

        $container->services['Pimcore\\Bundle\\DataImporterBundle\\Controller\\ConfigDataObjectController'] = $instance = new \Pimcore\Bundle\DataImporterBundle\Controller\ConfigDataObjectController(new \Pimcore\Bundle\DataImporterBundle\Preview\PreviewService(($container->privates['pimcore.dataImporter.preview.storage'] ?? $container->load('getPimcore_DataImporter_Preview_StorageService'))));

        $instance->setTokenResolver(($container->services['Pimcore\\Security\\User\\TokenStorageUserResolver'] ?? self::getTokenStorageUserResolverService($container)));
        $instance->setContainer(($container->privates['.service_locator.CgLZdtH'] ?? $container->load('get_ServiceLocator_CgLZdtHService'))->withContext('Pimcore\\Bundle\\DataImporterBundle\\Controller\\ConfigDataObjectController', $container));
        $instance->setPimcoreSerializer(($container->services['Pimcore\\Serializer\\Serializer'] ?? $container->load('getSerializerService')));

        return $instance;
    }
}
